### ISSUE TITLE
apple prototype not found

### ISSUE THREAD

**Issue by LottieVixen** [bahrmichael/factorio-tycoon#14]
trying to start the game with the latest release (0.0.9) and that alone, no other mods, fails

```
Failed to load mods: __tycoon__/data.lua:1:module __tycoon__/prototypes/items/apple not found; no such file __tycoon__/prototypes/items/apple.lua
stack traceback:
[C]: in function 'require'
__tycoon__/data.lua:1:in main chunk
```

**Comment by bahrmichael** [comment]
@LottieVixen Thank you for reporting this!

I just pushed a version 0.0.10 which hopefully fixes this. I tested this on the local source code, but not on the published mod. Maybe there's a difference how the game loads my source code vs. the published one that I don't understand yet.

If the upgrade to 0.0.10 doesn't fix it: Did you start a new game or load a previous savegame? In 0.0.9 I made changes to the names of items (e.g. renaming `apple` to `tycoon-apple` which may explain why the game can't find the apple anymore.=

**Comment by LottieVixen** [comment]
I forgot to mention the context in the issue, this was on initialization / starting the game.

not sure why but local vs published being different is interesting, 

enabling tycoon 0.0.10 didn't fix it either, upon loading the game (again before main menu, loading mod)
```
Failed to load mods: __tycoon__/data.lua:1: module prototypes/items/apple not found;  no such file __tycoon__/prototypes/items/apple.lua no such file __tycoon__/prototypes/items/apple.lua no such file __core__/lualib/prototypes/items/apple.lua
stack traceback:
	[C]: in function 'require'
	__tycoon__/data.lua:1: in main chunk
```

**Comment by bahrmichael** [comment]
Thank you! I'll continue looking into this and will ping you when I have an update.

**Comment by LottieVixen** [comment]
Found the issue prototypes isn't packaged at all, not sure what is causing it, peeking into the zip revealed this 
![image](https://github.com/bahrmichael/factorio-tycoon/assets/495512/0c7333ba-38b9-4b03-9ce3-23952810f347)

**Comment by bahrmichael** [comment]
> Found the issue prototypes isn't packaged at all, not sure what is causing it, peeking into the zip revealed this ![image](https://user-images.githubusercontent.com/495512/270318044-0c7333ba-38b9-4b03-9ce3-23952810f347.png)

@LottieVixen That's right! My publishing was broken and didn't include the (recently added) prototypes folder.

I fixed it in https://github.com/bahrmichael/factorio-tycoon/pull/16 and 0.0.11 should contain the fix in a few minutes.

Thank you so much for your help :)

**Comment by LottieVixen** [comment]
All good glad I could help, thank you for the quick support and bug fixing.
